"""Cuarta  migracion

Revision ID: 052eac051417
Revises: 113f91b44e63
Create Date: 2025-05-23 09:24:23.595038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '052eac051417'
down_revision: Union[str, None] = '113f91b44e63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rendimiento_final',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota_final', sa.Float(), nullable=False),
    sa.Column('fecha_calculo', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rendimiento_final_id'), 'rendimiento_final', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rendimiento_final_id'), table_name='rendimiento_final')
    op.drop_table('rendimiento_final')
    # ### end Alembic commands ###
