"""Tercera  migracion

Revision ID: 113f91b44e63
Revises: 7bf6d4e68b1a
Create Date: 2025-05-21 00:45:14.736203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '113f91b44e63'
down_revision: Union[str, None] = '7bf6d4e68b1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipoevaluaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_tipoevaluaciones_id'), 'tipoevaluaciones', ['id'], unique=False)
    op.create_table('peso_tipo_evaluacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('porcentaje', sa.Float(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('gestion_id', sa.Integer(), nullable=False),
    sa.Column('tipo_evaluacion_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gestion_id'], ['gestiones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipo_evaluacion_id'], ['tipoevaluaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peso_tipo_evaluacion_id'), 'peso_tipo_evaluacion', ['id'], unique=False)
    op.create_table('evaluaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('tipo_evaluacion_id', sa.Integer(), nullable=False),
    sa.Column('periodo_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipo_evaluacion_id'], ['tipoevaluaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluaciones_id'), 'evaluaciones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluaciones_id'), table_name='evaluaciones')
    op.drop_table('evaluaciones')
    op.drop_index(op.f('ix_peso_tipo_evaluacion_id'), table_name='peso_tipo_evaluacion')
    op.drop_table('peso_tipo_evaluacion')
    op.drop_index(op.f('ix_tipoevaluaciones_id'), table_name='tipoevaluaciones')
    op.drop_table('tipoevaluaciones')
    # ### end Alembic commands ###
