"""Primera migracion

Revision ID: 9fc9f8ce97af
Revises: 
Create Date: 2025-05-19 21:58:42.280459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fc9f8ce97af'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('nivel', sa.String(), nullable=False),
    sa.Column('paralelo', sa.String(), nullable=False),
    sa.Column('turno', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_cursos_id'), 'cursos', ['id'], unique=False)
    op.create_table('docentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=False),
    sa.Column('correo', sa.String(), nullable=False),
    sa.Column('genero', sa.String(), nullable=False),
    sa.Column('contrasena', sa.String(), nullable=False),
    sa.Column('is_doc', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_index(op.f('ix_docentes_id'), 'docentes', ['id'], unique=False)
    op.create_table('estudiantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('genero', sa.String(), nullable=False),
    sa.Column('url_imagen', sa.String(), nullable=True),
    sa.Column('nombre_tutor', sa.String(), nullable=True),
    sa.Column('telefono_tutor', sa.String(), nullable=True),
    sa.Column('direccion_casa', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estudiantes_id'), 'estudiantes', ['id'], unique=False)
    op.create_table('gestiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anio')
    )
    op.create_index(op.f('ix_gestiones_id'), 'gestiones', ['id'], unique=False)
    op.create_table('materias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_materias_id'), 'materias', ['id'], unique=False)
    op.create_table('curso_materia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curso_materia_id'), 'curso_materia', ['id'], unique=False)
    op.create_table('docente_materia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('docente_id', sa.Integer(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['docente_id'], ['docentes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_docente_materia_id'), 'docente_materia', ['id'], unique=False)
    op.create_table('inscripciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('gestion_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['estudiante_id'], ['estudiantes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gestion_id'], ['gestiones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inscripciones_id'), 'inscripciones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inscripciones_id'), table_name='inscripciones')
    op.drop_table('inscripciones')
    op.drop_index(op.f('ix_docente_materia_id'), table_name='docente_materia')
    op.drop_table('docente_materia')
    op.drop_index(op.f('ix_curso_materia_id'), table_name='curso_materia')
    op.drop_table('curso_materia')
    op.drop_index(op.f('ix_materias_id'), table_name='materias')
    op.drop_table('materias')
    op.drop_index(op.f('ix_gestiones_id'), table_name='gestiones')
    op.drop_table('gestiones')
    op.drop_index(op.f('ix_estudiantes_id'), table_name='estudiantes')
    op.drop_table('estudiantes')
    op.drop_index(op.f('ix_docentes_id'), table_name='docentes')
    op.drop_table('docentes')
    op.drop_index(op.f('ix_cursos_id'), table_name='cursos')
    op.drop_table('cursos')
    # ### end Alembic commands ###
